[package]
name = "ank"
description = "Arch new kernel?"
version = "1.0.0"
edition = "2024"
repository = "https://github.com/sermuns/ank"
license = "WTFPL"
categories = ["command-line-utilities"]
authors = ["Samuel Ã…kesson <sermuns@lysator.liu.se>"]

[dependencies]
