name: Release
on:
  push:
    tags:
      - "*"

env:
  CRATE_NAME: ank

jobs:
  github_build:
    name: Build release binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: dtolnay/rust-toolchain@stable

      - run: cargo build --release

      - name: Extract tag name
        shell: bash
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        id: extract_tag

      - name: Prepare artifacts
        run: |
          mkdir target/stage
          cd target/release
          tar czvf ../stage/${{ env.CRATE_NAME }}-${{ steps.extract_tag.outputs.tag }}-x86_64-unknown-linux-gnu.tar.gz ${{ env.CRATE_NAME }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.CRATE_NAME }}-${{ steps.extract_tag.outputs.tag }}-x86_64-unknown-linux-gnu.tar.gz
          path: target/stage/*
          overwrite: true

  github_release:
    name: Create GitHub Release
    needs: github_build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4

      - name: Extract version
        shell: bash
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        id: extract_version

      - name: Release notes
        run: |
          sed -n '/^## \[${{ steps.extract_version.outputs.version }}\].*$/,/^## /p' CHANGELOG.md | sed '$d' > RELEASE.md

      - name: Build | Publish
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.CRATE_NAME }}-*/${{ env.CRATE_NAME }}-*
          body_path: RELEASE.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
